---
output: html_document
editor_options:
  chunk_output_type: console
---

# Get and save Fair model data

```{r}
#| label: notes

# AG1 exog Percent of 16+ population 26-55 minus percent 16-25. BLS data. 1, 2, 3 -- working age minus college age
# AG2 exog Percent of 16+ population 56-65 minus percent 16-25. BLS data. 1, 2, 3 -- early retirement minus college age
# AG3 exog Percent of 16+ population 66+ minus percent 16-25. BLS data. 1, 2, 3   -- elderly minus college age

```

{{< include _setup.qmd >}}

```{r}
#| label: get-save-data
#| eval: false
#| output: false

source(here::here("R", "functions_eviews.R"))

fn <- "fmage.txt"
fpath <- fs::path(DFMFP, fn)

fmages <- get_eviews(fpath)

fmages |> 
  unnest(cols = data)

fn <- "fmdata.txt"
fpath <- fs::path(DFMFP, fn)
fmdata <- get_eviews(fpath)

fmobjects <- tibble::lst(fmages, fmdata)
saveRDS(fmobjects, fs::path(DDATA, "fmobjects.rds"))

# fmdata appears to include the data in fmages??

```

```{r}
#| echo: false
#| messages: false
#| notes: false
#| warnings: false

# put the following shortcode on a standalone line in any qmd file that uses this code:
# {{< include _load_data.qmd >}}

fmobjects <- readRDS(fs::path(DDATA, "fmobjects.rds"))
list2env(fmobjects, envir = .GlobalEnv)

```

# create needed variables

Naming convention: left to right

Example:

-   AA is wealth
-   AA_pop is wealth / population
-   AA_pop_ln is log(wealth(population))
-   AA_pop_ln_l1 is log(wealth / population) lagged once
-   AA_pop_ln_d1 is first difference of log(wealth / population)
-   AA_pop_ln_d1_l1 is lagged first difference of log(wealth / population)

```{r}
#| echo: false
#| messages: false
#| notes: false
#| warnings: false

# create all lhs and rhs variables
# EX_pop_ln_l1
# 

vars <- c("AA", "AG1", "AG2", "AG3", "CS", "EX", "POP", "RS", "YD") 
popvars <- c("AA", "CS", "EX", "YD")
lnvars <- paste0(popvars, "_pop")
# d1vars <-
l1vars <- c("AA_pop_ln", "AG1", "AG2", "AG3", "C2", "CS_pop_ln", "EX_pop_ln", "YD_pop_ln", "RS")
l2vars <- c("AA_pop_ln", "CS_pop_ln")

tmp2 <- count(fmdata, vname)

data1 <- fmdata |> 
  bind_rows(fmages)
tmp <- count(data1, vname)

data2 <- fmdata |> 
  filter(vname %in% vars) |>  
  unnest(cols = data) |> 
  pivot_wider(names_from = vname) |> 
  arrange(date) |> 
  mutate(idx = row_number(),
         C = 1,
         C2 = case_when(
           date < T1 ~ 0,
           date < T2 ~ idx - idx[date == T1],
           date >= T2 ~ idx[date == T2] - idx[date == T1],
           .default = NA_real_)) |> 
  relocate(C, CS, .after = date) |> 
  select(-idx, -start, -end) |> 
  mutate(across(all_of(popvars),
                list(pop = \(x) x / POP)),
         across(all_of(lnvars),
                log,
                .names = "{.col}_ln"),
         across(all_of(l1vars),
                       \(x) lag(x, 1),
                       .names = "{.col}_l1"),
         across(all_of(l2vars),
                       \(x) lag(x, 2),
                       .names = "{.col}_l2"))
  
data2

data3 <- data2 |> 
  na.omit() |>  # drop any row that has an NA in any variable
  filter(date >= smpl$start,
         date <= smpl$end) |> 
  pivot_longer(cols = -date) |> 
  arrange(str_to_upper(name), date)
glimpse(data3)

data4 <- data3 |> 
  pivot_wider()
data4  

saveRDS(data4, fs::path(DDATA, "fmall.rds"))

```
